name: Package fotowall
on:
  repository_dispatch:
    types:
    - package-master
    - package-release
  push:
    paths-ignore:
    - doc/**
    - README.md
    - ".github/workflows/build.yml"
    - ".pre-commit-config.yaml"
    branches:
    - "**"
    tags:
    - v*
  pull_request:
    branches:
    - "**"
jobs:
  package:
    uses: jrl-umi3218/github-actions/.github/workflows/package-project.yml@master
    with:
      latest-cmake: true
      matrix: |
          {
            "dist": ["focal", "jammy"],
            "arch": ["amd64"]
          }
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
