name: Package fotowall
on:
  repository_dispatch:
    types:
    - package-master
    - package-release
  push:
    paths-ignore:
    - doc/**
    - README.md
    - ".github/workflows/build.yml"
    - ".pre-commit-config.yaml"
    branches:
    - "**"
    tags:
    - v*
  pull_request:
    branches:
    - "**"
jobs:
  working-directory:
    runs-on: ubuntu-latest
    steps:
    - name: Free-up space
      run: |
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android
  package:
    uses: arntanguy/github-actions/.github/workflows/package-project.yml@topic/git
    with:
      latest-cmake: true
      matrix: |
          {
            "dist": ["focal", "jammy"],
            "arch": ["amd64"]
          }
      head-repo: "arntanguy/head"
      stable-repo: "arntanguy/stable"
      update-stable-and-head: true
    secrets:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
